### ISSUE TITLE
Objects appear at different sizes and places on different screen sizes/devices

### ISSUE THREAD

**Issue by szabadimiklos** [AR-js-org/AR.js#109] opened 2020-05-07 14:13 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
If using AR.js A-frame NFT version on _different devices_, objects appear at different sizes and different locations relative to the marker image. Can't really describe the problem with words, or what causes it, but in your NFT example it also occurs
[(https://github.com/AR-js-org/AR.js/blob/master/aframe/examples/image-tracking/nft/index.html)](https://github.com/AR-js-org/AR.js/blob/master/aframe/examples/image-tracking/nft/index.html)
Also I've attached some pictures below.
Seems to be realted to this issue so I'll describe this too:
when moving the camera around the marker image, the entire scene seems to move away from the marker, like the scene is not exactly placed on it. 

Here is a picture of the basic isssue on Desktop
![desktop](https://user-images.githubusercontent.com/51154354/81302224-5e41c580-907a-11ea-8720-75415ed5351d.jpg)

And on my Phone. You can see thet the model is larger than on Desktop and also appears at a different location
![phone](https://user-images.githubusercontent.com/51154354/81302276-71ed2c00-907a-11ea-97f2-053e9c2dc05a.jpg)

**If the current behavior is a bug, please provide the steps to reproduce.**
Check your AR.js A-frame NFT example on different devices with different screen sizes/cameras
[(https://github.com/AR-js-org/AR.js/blob/master/aframe/examples/image-tracking/nft/index.html)](https://github.com/AR-js-org/AR.js/blob/master/aframe/examples/image-tracking/nft/index.html)
You can also try to view the T-rex from different angles, you will see that the T-rex is moving away from it's original location.

**Please mention other relevant information such as the browser version, Operating System and Device Name**
I've experienced this issue regadless the OS/browser (Tested it on Windows/Chrome, Android/Chrome, iOS/Chrome, iOS/Safari)

**What is the expected behavior?**
The scene should look exactly the same on every device, the objects locations and sizes shouldn't be affected by the screen/camera ratio and the camera's angle on the marker image.
Eg.: If we place the T-rex to the middle of the marker, it should appear there regardless of the device we use. Also when moving around the scene, the T-rex should stay in the middle.

**If this is a feature request, what is motivation or use case for changing the behavior?**
It's not a feature request

**Comment by JamesBotterill** [comment] 2020-05-10 12:19
This is a dupe of issue #4 from looking at it

**Closed** 2020-05-20 13:54 UTC
Labels: duplicate, nft

**Comment by patrickoshaughnessey** [comment] 2020-07-07 21:31
I have seen this same behavior using the NFT three.js sample. I added a red sphere to 0,0, and it shows up in different places depending upon the resolution and orientation of the phone (landscape vs. portrait). Is this really a duplicate of #4? #4 seems to be more about making 0,0 be the center of the marker, which I agree would be convenient. However, this issue is about making the 0,0,0 coordinate be consistent, even if it is the lower left (which it is now). Attached some images I took on my Galaxy Tab S6 + Chrome + Android 10 at 640x480 and 480x640, in both portrait and landscape.
<img width="1054" alt="480x640 Landscape GalaxyTabS6 Chrome83 0 4103 106 Android10" src="https://user-images.githubusercontent.com/115180/86845524-4208d780-c06f-11ea-88f1-e5e67eb288cb.png">
<img width="859" alt="480x640 Portrait GalaxyTabS6 Chrome83 0 4103 106 Android10" src="https://user-images.githubusercontent.com/115180/86845526-42a16e00-c06f-11ea-9170-8f6c07eff9ff.png">
<img width="866" alt="640x480 Portrait GalaxyTabS6 Chrome83 0 4103 106 Android10" src="https://user-images.githubusercontent.com/115180/86845527-433a0480-c06f-11ea-8c51-89b82bf545a6.png">
<img width="1055" alt="640x480 Landscape GalaxyTabS6 Chrome83 0 4103 106 Android10" src="https://user-images.githubusercontent.com/115180/86845528-433a0480-c06f-11ea-9052-19574898743f.png">
