### ISSUE TITLE
Image tracking coordinate system origin

### ISSUE THREAD

**Issue by andypotato** [AR-js-org/AR.js#63] opened 2020-03-20 04:51 UTC
For marker based tracking the coordinate system origin is the center point of the marker square. Positioning an object at (0, 0, 0) will make it appear exactly at the center of the marker.

For image marker the coordinate system origin seems to be in a very weird place. It requires huge offsets like (100, 200, 0) to make them appear even close to the image marker. Also there seems to be a Z-offset which causes objects to hover around the marker in weird ways.

Question therefore: How is the origin placed in case of image markers and could we improve this to be consistent with "normal" markers?

**Comment by nicolocarpignoli** [comment] 2020-03-20 06:48
duplicate of: https://github.com/AR-js-org/AR.js/issues/4

continue there :)

**Closed by nicolocarpignoli** 2020-03-20 06:48 UTC
