### ISSUE TITLE
404 error on examples from docs

### ISSUE THREAD

**Issue by IgorDePaula** [AR-js-org/AR.js#382] opened 2022-01-27 22:15 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Not work, apper 404 error to loading model

**If the current behavior is a bug, please provide the steps to reproduce.**
I download the image (https://raw.githack.com/AR-js-org/AR.js/master/aframe/examples/image-tracking/nft/trex-image-big.jpeg)
and access the address (https://ar-js-org.github.io/AR.js/aframe/examples/image-tracking/nft/) with my pc

**Please mention other relevant information such as the browser version, Operating System and Device Name**
Ubuntu 21.10 - Firefox 

**What is the expected behavior?**

Render a Dino figure

**If this is a feature request, what is motivation or use case for changing the behavior?**

![photo_2022-01-27_19-14-46](https://user-images.githubusercontent.com/2833993/151452594-946be8c6-0e45-439c-b0c4-92c82f3d5046.jpg)

**Comment by kalwalt** [comment] 2022-02-04 16:36
@IgorDePaula thank you , we know this. The problem is gh-pages that require different path. We didn't find a easy solution yet.
Closing because a duplicated issue https://github.com/AR-js-org/AR.js/issues/364

**Closed by kalwalt** 2022-02-04 16:36 UTC
Labels: bug, duplicate

**Comment by IgorDePaula** [comment] 2022-02-05 23:47
@kalwalt Thank you for your answer.

**Comment by IgorDePaula** [comment] 2022-02-08 22:00
@kalwalt do you try host de app in netlify?
