### ISSUE TITLE
image tracking not working

### ISSUE THREAD

**Issue by Marcus5234** [AR-js-org/AR.js#11] opened 2020-03-02 11:58 UTC
I just tried the example in the readme, and got this error:

![image](https://user-images.githubusercontent.com/49681242/75674502-eadb9c00-5c63-11ea-9a8e-508231c680ff.png)

**Comment by JamesBotterill** [comment] 2020-03-02 12:10
@Marcus5234  this is a dupe of #10 

I would close this

**Closed** 2020-03-02 12:19 UTC
