### ISSUE TITLE
The Default geolocation example is broken on iOS 14.4.2

### ISSUE THREAD

**Issue by jonnypage** [AR-js-org/AR.js#254] opened 2021-04-26 22:06 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

On iOS 14.4.2 the default geolocation example on [this page](https://ar-js-org.github.io/AR.js-Docs/location-based-tutorial/) does not work. It errors out with an unhandled promise in `aframe-ar-nft.js` on `line 4639` The camera does not work and shows a static frame from the camera.

<img width="796" alt="arjs-error-screenshot" src="https://user-images.githubusercontent.com/6945535/116156404-a8b3bc00-a6a8-11eb-85c3-b5fee089961a.png">

It seems to have to do with setting `videoTexture` to `true` in the `arjs` attribute in `a-scene`. It works properly when removed. 

All a-frame/iOS permissions have been accepted.

**If the current behavior is a bug, please provide the steps to reproduce.**

Copy/paste the example and run it on a server with a ssl certificate

**Please mention other relevant information such as the browser version, Operating System and Device Name**

This occurs and is tested on an iPhone SE, iPhone 6s Plus and iPhone 8 Plus running iOS 14.4.2 under Safari, Chrome and Firefox.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Comment by kalwalt** [comment] 2021-04-26 22:17
Hi @jonnypage  thanks for reporting this, @nickw1 could you look at this? Maybe is related to the issue we have in the ES6 branch?

**Comment by nickw1** [comment] 2021-04-27 11:39
@jonnypage is this with the latest master or with one of the releases (eg. 3.3.1)?

An iOS bug with videoTexture in which the screen froze was recently fixed and is in master:
https://github.com/AR-js-org/AR.js/pull/235

@kalwalt the ES6 branch issue is the opposite condition, i.e. when `videoTexture` is not defined, so I suspect it's something different.

**Comment by nickw1** [comment] 2021-04-27 11:41
@jonnypage also, is it only in that specific version of iOS? Do you have access to any older versions of iOS to test? Thanks.

**Comment by jonnypage** [comment] 2021-04-27 14:08
The bug was happening with a older version we had locally, as well as with the example from the docs using the CDN which looks like it points to master. I just copy/pasted that html code on top of mine and saved over as a sanity test, and it still failed.

I don't I have any iOS devices that are not running 14.4.2. 

I will say the 2 iPads I have access to (mini and air 3) don't throw the error, but they do not have gps chips and ovbiously do not work with geolocation.

**Comment by nickw1** [comment] 2021-04-27 16:31
@jonnypage ah, I think the issue is that the recent commit #235 was merged with `dev`, not `master`. So the master branch does not have this fix yet.

@kalwalt @nicolocarpignoli OK to merge this update into master?

**Comment by nicolocarpignoli** [comment] 2021-04-27 17:39
@nickw1 Yes, you can also release a new version. You can find all the steps to do that on the Readme. Go for it

**Comment by kalwalt** [comment] 2021-04-28 13:05
@nickw1 if you merge the dev into master i think you should syncing the dev branch with the master, i have applied the cors proxy changes only to the master branch.

**Comment by nickw1** [comment] 2021-04-28 18:13
@kalwalt ok will do when I have a moment.

**Comment by nickw1** [comment] 2021-05-01 10:13
@jonnypage OK do you want to test now? I have now merged dev into master so it should include this fix. Thanks.

**Comment by jonnypage** [comment] 2021-05-03 21:09
@nickw1 @kalwalt Tested with the new master branch from the CDN and it seems to be working!

Cheers!

**Closed** 2021-05-03 21:09 UTC
Labels: bug, location based
