### ISSUE TITLE
Location Base - Entity is following

### ISSUE THREAD

**Issue by allestaire** [AR-js-org/AR.js#592] opened 2024-01-12 01:08 UTC
The entity is following the camera instead of being still on the configured lat long,

Can anyone point out why is this happening?
I tried to move up to 10meters but the object I set on the location still in me. seems like a ghost

```html

<!DOCTYPE html>
<html>
<head>
<title>AR.js A-Frame</title>
<script src="https://aframe.io/releases/1.3.0/aframe.min.js"></script>
<script src="https://unpkg.com/aframe-look-at-component@0.8.0/dist/aframe-look-at-component.min.js"></script>
<!-- Assumes AR.js build is in the 'AR.js' directory -->
<script type='text/javascript' src='/ar-threex-location-only.js'></script>
<script type='text/javascript' src='/aframe-ar.js'></script>
</head>
<body>
<!-- 
Examples: https://github.com/AR-js-org/AR.js/blob/master/aframe/examples/new-location-based/always-face-user/index.html
This is using a simulated location. If testing on a mobile device, remove the 
'simulateLatitude' and 'simulateLongitude' properties from 'gps-new-camera' and
change the 'latitude' and 'longitude' properties to a location around 0.001 
degrees from your real location.
-->
<a-scene vr-mode-ui='enabled: false' arjs='sourceType: webcam; videoTexture: true; debugUIEnabled: false' renderer='antialias: true; alpha: true'>
	<a-camera gps-new-camera='gpsMinDistance: 1;'></a-camera>
	<a-entity material='color: red' geometry='primitive: box' gps-new-entity-place="latitude: 8.477820; longitude: 124.642536" scale="10 10 10"></a-entity>
</a-scene>
	
</body>
</html>

```

**Comment by iaminkrypn0os** [comment] 2024-03-20 22:23
The same is happening to me. Sad to not find an answer here.

**Comment by nickw1** [comment] 2024-04-28 08:48
This is the same issue as #278 by the looks of things.

Unfortunately it hasn't been resolved yet, it looks like it's a device-specific issue, perhaps due to specific device sensors.

What might help is opening a new issue in which people can list exact device models/OS versions that have this error, in order to identify the cause.

Apologies for the late reply, I will admit I have little time for AR.js these days: more than anything else we need more developers!

**Comment by nickw1** [comment] 2024-04-28 08:51
Issue created. See #603.

**Comment by nickw1** [comment] 2024-09-12 18:56
Closing as it is a duplicate of other issues e.g. #278 .

**Closed by nickw1** 2024-09-12 18:56 UTC
